import './globals.css'

import type { Metadata } from 'next'
import { Nunito_Sans as NinitoSans } from 'next/font/google'

import { Header } from '@/components/header'

const nunitoSans = NinitoSans({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-nunito-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.variable}>
        <Header />
        <div className="w-full max-w-4xl px-4 font-sans md:mx-auto">
          {children}
        </div>
      </body>
    </html>
  )
}
